name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify
        run: echo "CI działa ✅"
