name: JSON Validate
on: [push, pull_request]
jobs:
  jsonlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          for f in $(git ls-files '*.json'); do
            jq empty "$f"; done
