name: Markdown Spell
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install aspell
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en aspell-pl
      - name: Check md
        run: |
          for f in $(git ls-files '*.md'); do
            aspell -l pl list < "$f" | sort -u | sed "s/^/MD typo: /"; done || true
