name: pre-commit
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pipx install pre-commit && pre-commit run --all-files
